MODEL_REGISTRY = {
    "TreeNetDenoise": {
        "url": "https://github.com/rymuelle/RawForge/releases/download/onnx_v1.0.0/ShadowWeightedL1.onnx",
        "filename": "ShadowWeightedL1.onnx",
        "torchurl": "https://github.com/rymuelle/RawRefinery/releases/download/v1.2.1-alpha/ShadowWeightedL1.pt",
        "torchfilename": "ShadowWeightedL1.pt",
        "max_iso": 65535,
        "demosaicing": "Malvar2004",
        "conditioning": True,
    },
    "TreeNetDenoiseLight": {
        "url": "    https://github.com/rymuelle/RawForge/releases/download/onnx_v1.0.0/ShadowWeightedL1_light.onnx",
        "filename": "ShadowWeightedL1_light.onnx",
        "torchurl": "https://github.com/rymuelle/RawRefinery/releases/download/v1.2.1-alpha/ShadowWeightedL1_light.pt",
        "torchfilename": "ShadowWeightedL1_light.pt",
        "max_iso": 65535,
        "demosaicing": "Malvar2004",
        "conditioning": True,

    },
    "TreeNetDenoiseSuperLight": {
        "url": "https://github.com/rymuelle/RawForge/releases/download/onnx_v1.0.0/ShadowWeightedL1_super_light.onnx",
        "filename": "ShadowWeightedL1_super_light.onnx",
        "torchurl": "https://github.com/rymuelle/RawRefinery/releases/download/v1.2.1-alpha/ShadowWeightedL1_super_light.pt",
        "torchfilename": "ShadowWeightedL1_super_light.pt",
        "max_iso": 65535,
        "demosaicing": "Malvar2004",
        "conditioning": True,
    },
    "TreeNetDenoiseHeavy": {
        "url": "https://github.com/rymuelle/RawForge/releases/download/onnx_v1.0.0/ShadowWeightedL1_24_deep_500.onnx",
        "filename": "ShadowWeightedL1_24_deep_500.onnx",
        "torchurl": "https://github.com/rymuelle/RawRefinery/releases/download/v1.2.1-alpha/ShadowWeightedL1_24_deep_500.pt",
        "torchfilename": "ShadowWeightedL1_24_deep_500.pt",
        "max_iso": 65535,
        "demosaicing": "Malvar2004",
        "conditioning": True,
    },
    "Deblur": {
        "url": "https://github.com/rymuelle/RawForge/releases/download/onnx_v1.0.0/realblur_gamma_140.onnx",
        "filename": "realblur_gamma_140.onnx",
        "torchurl": "https://github.com/rymuelle/RawRefinery/releases/download/v1.2.1-alpha/realblur_gamma_140.pt",
        "torchfilename": "realblur_gamma_140.pt",
        "demosaicing": "Malvar2004",
        "conditioning": True,
    },
    "DeepSharpen": {
        "url": "https://github.com/rymuelle/RawForge/releases/download/onnx_v1.0.0/Deblur_deep_24.onnx",
        "filename": "Deblur_deep_24.onnx",
        "torchurl": "https://github.com/rymuelle/RawRefinery/releases/download/v1.2.1-alpha/Deblur_deep_24.pt",
        "torchfilename": "Deblur_deep_24.pt",
        "demosaicing": "Malvar2004",
        "conditioning": True,
    },
    "TreeNetDenoiseXTrans": {
        "url": "https://github.com/rymuelle/RawForge/releases/download/onnx_v1.0.0/xtrans_fixed_exposure_no_conditioning_400.onnx",
        "filename": "xtrans_fixed_exposure_no_conditioning_400.onnx",
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/xtrans_v1.0.0/xtrans_fixed_exposure_no_conditioning_400.pt",
        "torchfilename": "xtrans_fixed_exposure_no_conditioning_400.pt",
        "demosaicing": "rawpy",
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
        "cond_scale": 0,
    },
    "RestormerXTrans": {
        "url": "https://github.com/rymuelle/RawForge/releases/download/onnx_v1.0.0/restormer.onnx",
        "filename": "restormer.onnx",
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/xtrans_v1.0.0/restormer.pt",
        "torchfilename": "restormer.pt",
        "demosaicing": "rawpy",
        "conditioning": True,
        "batch_size": 1,
    },
    "XFormerXTrans2": {
        "url": "https://github.com/rymuelle/RawForge/releases/download/onnx_v1.0.0/xformer_fp16.onnx",
        "filename": "xformer_fp16.onnx",
        "demosaicing": "rawpy",
        "conditioning": False,
        "batch_size": 1,
    },
    "XFormerDenoise": {
        "url": "https://github.com/rymuelle/RawForge/releases/download/onnx_v1.0.0/xformer_static.onnx",
        "filename": "xformer_static.onnx",
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/xtrans_v1.0.0/xformer.pt",
        "torchfilename": "xformer.pt",
        "demosaicing": "rawpy",
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
    },


    "DemoNAFNet": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DemoNAFNet_noraf_cont_swl_0p1.pt",
        "torchfilename": "DemoNAFNet_noraf_cont_swl_0p1.pt",
        "demosaicing": "sixchan",
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
    },
    "DemoNAFNet_l1": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DemoNAFNet_noraf_cont_cont.pt",
        "torchfilename": "DemoNAFNet_noraf_cont_cont.pt",
        "demosaicing": "sixchan",
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
    },
    "DemoNAFNet_noraf_cont_lpips_p1": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DemoNAFNet_noraf_cont_lpips_p1.pt",
        "torchfilename": "DemoNAFNet_noraf_cont_lpips_p1.pt",
        "demosaicing": "sixchan",
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
    },
    "Demosaic_resize_2_32_long": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/Demosaic_resize_2_32_long.pt",
        "torchfilename": "Demosaic_resize_2_32_long.pt",
        "demosaicing": "sixchan",
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
    },
    "DemoNAFNet_noraf_augment": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DemoNAFNet_noraf_augment.pt",
        "torchfilename": "DemoNAFNet_noraf_augment.pt",
        "demosaicing": "sixchan",
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
    },
    "DemoNAFNetDIT": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DemoNAFNetDIT.pt",
        "torchfilename": "DemoNAFNetDIT.pt",
        "demosaicing": "sixchan",
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
    },
    "DemoNAFNet_noraf_only_rotation_augment": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DemoNAFNet_noraf_only_rotation_augment.pt",
        "torchfilename": "DemoNAFNet_noraf_only_rotation_augment.pt",
        "demosaicing": "sixchan",
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
    },
    "DemoNAFNet_noraf_gamma_loss": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DemoNAFNet_noraf_gamma_loss.pt",
        "torchfilename": "DemoNAFNet_noraf_gamma_loss.pt",
        "demosaicing": "sixchan",
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
    },

    
    "DemoNAFNet_noraf_cont_cont_black_level": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DemoNAFNet_noraf_cont_cont_black_level.pt",
        "torchfilename": "DemoNAFNet_noraf_cont_cont_black_level.pt",
        "demosaicing": "sixchan",
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
        "subtract_bl": True,
    },
    "DemoNAF_heavy_no_gamma": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DemoNAF_heavy_no_gamma.pt",
        "torchfilename": "DemoNAF_heavy_no_gamma.pt",
        "demosaicing": "sixchan",
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
        "subtract_bl": True,
    },

    "DemoNAFNetMamba_test_highlight": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DemoNAFNetMamba_test_highlight.pt",
        "torchfilename": "DemoNAFNetMamba_test_highlight.pt",
        "demosaicing": "sixchan",
        "image_scale": 0.52,
        "image_clip": 0.5,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
        "subtract_bl": True,
    },

    "DemoNAF_heavy_no_gamma_cont_no_bl_no_ccm": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DemoNAF_heavy_no_gamma_cont_no_bl_no_ccm.pt",
        "torchfilename": "DemoNAF_heavy_no_gamma_cont_no_bl_no_ccm.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
        "subtract_bl": False,
    },

    "DemoNAFNet_noraf_ShadowWeightedL1": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DemoNAFNet_noraf_ShadowWeightedL1.pt",
        "torchfilename": "DemoNAFNet_noraf_ShadowWeightedL1.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
        "subtract_bl": False,
    },


    "DemoRestormer_256": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DemoRestormer_256.pt",
        "torchfilename": "DemoRestormer_256.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
        "subtract_bl": False,
    },
    "DemoNAFNet_noraf_ShadowWeightedL1_v2": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DemoNAFNet_noraf_ShadowWeightedL1_v2.pt",
        "torchfilename": "DemoNAFNet_noraf_ShadowWeightedL1_v2.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
        "subtract_bl": False,
    },
    "DemoNAFNet_noraf_ShadowWeightedL1_short": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DemoNAFNet_noraf_ShadowWeightedL1_short.pt",
        "torchfilename": "DemoNAFNet_noraf_ShadowWeightedL1_short.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
        "subtract_bl": False,
    },
    "DemoNAFNet_noraf_ShadowWeightedL1_Sigmoid": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DemoNAFNet_noraf_ShadowWeightedL1_Sigmoid.pt",
        "torchfilename": "DemoNAFNet_noraf_ShadowWeightedL1_Sigmoid.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
        "subtract_bl": False,
    },
    "DemoRestormer_noraf_ShadowWeightedL1": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DemoRestormer_noraf_ShadowWeightedL1.pt",
        "torchfilename": "DemoRestormer_noraf_ShadowWeightedL1.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
        "subtract_bl": False,
    },
    "DemoNAFNet_noraf_ShadowWeightedL1_Sigmoid_low_res_heavy": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DemoNAFNet_noraf_ShadowWeightedL1_Sigmoid_low_res_heavy.pt",
        "torchfilename": "DemoNAFNet_noraf_ShadowWeightedL1_Sigmoid_low_res_heavy.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
        "subtract_bl": False,
    },

    "DemoNAFNet_noraf_ShadowWeightedL1_Sigmoid_v2": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DemoNAFNet_noraf_ShadowWeightedL1_Sigmoid_v2.pt",
        "torchfilename": "DemoNAFNet_noraf_ShadowWeightedL1_Sigmoid_v2.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
        "subtract_bl": False,
    },

     "DemoRestormer_noraf_ShadowWeightedL1_3k": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DemoRestormer_noraf_ShadowWeightedL1_3k.pt",
        "torchfilename": "DemoRestormer_noraf_ShadowWeightedL1_3k.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
        "subtract_bl": False,
    },   
     "DiT_test": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DiT_test.pt",
        "torchfilename": "DiT_test.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
        "subtract_bl": False,
    },   
     "DemoRestormerDiT_test": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DemoRestormerDiT_test.pt",
        "torchfilename": "DemoRestormerDiT_test.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
        "subtract_bl": False,
    },  
     "DemoRestormerDiT_test_v2": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DemoRestormerDiT_test_v2.pt",
        "torchfilename": "DemoRestormerDiT_test_v2.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
        "subtract_bl": False,
    },  
     "Restomer_low_res": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/Restomer_low_res.pt",
        "torchfilename": "Restomer_low_res.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 4096,
        "subtract_bl": False,
    }, 
     "Restomer_low_res_358": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/Restomer_low_res_358.pt",
        "torchfilename": "Restomer_low_res_358.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 1024,
        "subtract_bl": True,
    }, 

     "Restomer_low_res_subtract_bl": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/Restomer_low_res_subtract_bl.pt",
        "torchfilename": "Restomer_low_res_subtract_bl.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 1024,
        "subtract_bl": True,
        "image_clip": True,
    }, 
     "Restomer_low_res_light_bl_subtracted": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/Restomer_low_res_light_bl_subtracted.pt",
        "torchfilename": "Restomer_low_res_light_bl_subtracted.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
        "subtract_bl": True,
        "image_clip": True,
    }, 
     "BaseDenoisingSIDD_mask": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/BaseDenoisingSIDD_mask.pt",
        "torchfilename": "BaseDenoisingSIDD_mask.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
        "subtract_bl": True,
        "image_clip": True,
    }, 
     "BaseDenoisingSIDD_mask_1650": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/BaseDenoisingSIDD_mask_1650.pt",
        "torchfilename": "BaseDenoisingSIDD_mask_1650.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 1024,
        "subtract_bl": True,
        "image_clip": True,
    }, 
     "BaseDenoisingSIDD_mask_1650_retraining": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/BaseDenoisingSIDD_mask_1650_retraining.pt",
        "torchfilename": "BaseDenoisingSIDD_mask_1650_retraining.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
        "subtract_bl": True,
        "image_clip": True,
    }, 
     "BaseDenoisingSIDD_mask_1650_deeper": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/BaseDenoisingSIDD_mask_1650_deeper.pt",
        "torchfilename": "BaseDenoisingSIDD_mask_1650_deeper.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
        "subtract_bl": True,
        "image_clip": True,
    }, 
     "Demosaic_resize_shallow_test_mask": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/Demosaic_resize_shallow_test_mask.pt",
        "torchfilename": "Demosaic_resize_shallow_test_mask.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
        "subtract_bl": True,
        "image_clip": True,
    }, 
     "demosacing_test": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/demosacing_test.pt",
        "torchfilename": "demosacing_test.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 1024,
        "subtract_bl": True,
        "image_clip": True,
    }, 
      "DemoSepRestormerDiT_demo_first_1650": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DemoSepRestormerDiT_demo_first_1650.pt",
        "torchfilename": "DemoSepRestormerDiT_demo_first_1650.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
        "subtract_bl": True,
        "image_clip": True,
    },    
      "BaseDenoisingSIDD_mask_1650_deeper_256": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/BaseDenoisingSIDD_mask_1650_deeper_256.pt",
        "torchfilename": "BaseDenoisingSIDD_mask_1650_deeper_256.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
        "subtract_bl": True,
        "image_clip": True,
    },    
       "BaseDenoisingSIDD_mask_360_256": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/BaseDenoisingSIDD_mask_360_256.pt",
        "torchfilename": "BaseDenoisingSIDD_mask_360_256.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
        "subtract_bl": True,
        "image_clip": True,
    },    
       "BaseDenoisingSIDD_mask_256_360_t2": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/BaseDenoisingSIDD_mask_256_360_t2.pt",
        "torchfilename": "BaseDenoisingSIDD_mask_256_360_t2.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
        "subtract_bl": True,
        "image_clip": True,
    },      
        "SixChanNAFDiT": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/SixChanNAFDiT.pt",
        "torchfilename": "SixChanNAFDiT.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
        "subtract_bl": True,
        "image_clip": True,
    },
        "BaseDenoisingSIDD_mask_1650_deeper_768": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/BaseDenoisingSIDD_mask_1650_deeper_768.pt",
        "torchfilename": "BaseDenoisingSIDD_mask_1650_deeper_768.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 768,
        "subtract_bl": True,
        "image_clip": True,
    },

        "BaseDenoisingSIDD_mask_1650_deeper_768_cont": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/BaseDenoisingSIDD_mask_1650_deeper_768_cont.pt",
        "torchfilename": "BaseDenoisingSIDD_mask_1650_deeper_768_cont.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 768,
        "subtract_bl": True,
        "image_clip": True,
    },

        "SixChanRestormerDiT_DiT_test": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/SixChanRestormerDiT_DiT_test.pt",
        "torchfilename": "SixChanRestormerDiT_DiT_test.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
        "subtract_bl": True,
        "image_clip": True,
    },

        "SixChanRestormerDiT_DiT_test_cont": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/SixChanRestormerDiT_DiT_test_cont.pt",
        "torchfilename": "SixChanRestormerDiT_DiT_test_cont.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
        "subtract_bl": True,
        "image_clip": True,
    },
        "SixChanRestormerDiT_DiT_test_cont_768": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/SixChanRestormerDiT_DiT_test_cont_768.pt",
        "torchfilename": "SixChanRestormerDiT_DiT_test_cont_768.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 1024,
        "subtract_bl": True,
        "image_clip": True,
    },
        "Demosaic_resize_shallow_test_mask_cont": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/Demosaic_resize_shallow_test_mask_cont.pt",
        "torchfilename": "Demosaic_resize_shallow_test_mask_cont.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
        "subtract_bl": False,
        "image_clip": True,
    },
        "DemoNAFNet_no_sca": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DemoNAFNet_no_sca.pt",
        "torchfilename": "DemoNAFNet_no_sca.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
        "subtract_bl": False,
        "image_clip": True,
    },
        "DemoRestormerDiT_to_demo": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DemoRestormerDiT_to_demo.pt",
        "torchfilename": "DemoRestormerDiT_to_demo.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 768,
        "subtract_bl": True,
        "image_clip": True,
    },
        "DemoRestormerDiT_to_demo_cont": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DemoRestormerDiT_to_demo_cont.pt",
        "torchfilename": "DemoRestormerDiT_to_demo_cont.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
        "subtract_bl": True,
        "image_clip": True,
    },
        "DemoRestormerDiT_to_demo_cont_cont_768": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DemoRestormerDiT_to_demo_cont_cont_768.pt",
        "torchfilename": "DemoRestormerDiT_to_demo_cont_cont_768.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 768,
        "subtract_bl": True,
        "image_clip": True,
    },
        "DemoNAFNetDiTNoSCA_gelu_gate": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DemoNAFNetDiTNoSCA_gelu_gate.pt",
        "torchfilename": "DemoNAFNetDiTNoSCA_gelu_gate.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 768,
        "subtract_bl": True,
        "image_clip": True,
    },
        "DemoRestormerDiT_to_demo_cont_cont_768_texture": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DemoRestormerDiT_to_demo_cont_cont_768_texture.pt",
        "torchfilename": "DemoRestormerDiT_to_demo_cont_cont_768_texture.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 512,
        "subtract_bl": True,
        "image_clip": True,
    },
        "DemoRestormerDiT_to_demo_cont_cont_768_texture_v2": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DemoRestormerDiT_to_demo_cont_cont_768_texture_v2.pt",
        "torchfilename": "DemoRestormerDiT_to_demo_cont_cont_768_texture_v2.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 512,
        "subtract_bl": True,
        "image_clip": True,
    },
        "JDD": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DemoRestormerDiT_to_demo_cont_cont_768_RawNIND.pt",
        "torchfilename": "DemoRestormerDiT_to_demo_cont_cont_768_RawNIND.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 768,
        "subtract_bl": False,
        "image_clip": True,
    },
        "DemoRestormerDiT_to_demo_cont_cont_768_RawNIND_256": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DemoRestormerDiT_to_demo_cont_cont_768_RawNIND_256.pt",
        "torchfilename": "DemoRestormerDiT_to_demo_cont_cont_768_RawNIND_256.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
        "subtract_bl": False,
        "image_clip": True,
    },
        "DemoRestormerDiT_to_demo_cont_cont_768_RawNIND_256_bl": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DemoRestormerDiT_to_demo_cont_cont_768_RawNIND_256_bl.pt",
        "torchfilename": "DemoRestormerDiT_to_demo_cont_cont_768_RawNIND_256_bl.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
        "subtract_bl": True,
        "image_clip": True,
    },
}

for model_config in MODEL_REGISTRY.values():
    model_config.setdefault("tile_size", 256)
    model_config.setdefault("tile_overlap", 0.25)
    model_config.setdefault("batch_size", 1)
    model_config.setdefault("conditioning", False)