MODEL_REGISTRY = {
    "TreeNetDenoise": {
        "url": "https://github.com/rymuelle/RawForge/releases/download/onnx_v1.0.0/ShadowWeightedL1.onnx",
        "filename": "ShadowWeightedL1.onnx",
        "torchurl": "https://github.com/rymuelle/RawRefinery/releases/download/v1.2.1-alpha/ShadowWeightedL1.pt",
        "torchfilename": "ShadowWeightedL1.pt",
        "max_iso": 65535,
        "demosaicing": "Malvar2004",
        "conditioning": True,
    },
    "TreeNetDenoiseLight": {
        "url": "    https://github.com/rymuelle/RawForge/releases/download/onnx_v1.0.0/ShadowWeightedL1_light.onnx",
        "filename": "ShadowWeightedL1_light.onnx",
        "torchurl": "https://github.com/rymuelle/RawRefinery/releases/download/v1.2.1-alpha/ShadowWeightedL1_light.pt",
        "torchfilename": "ShadowWeightedL1_light.pt",
        "max_iso": 65535,
        "demosaicing": "Malvar2004",
        "conditioning": True,

    },
    "TreeNetDenoiseSuperLight": {
        "url": "https://github.com/rymuelle/RawForge/releases/download/onnx_v1.0.0/ShadowWeightedL1_super_light.onnx",
        "filename": "ShadowWeightedL1_super_light.onnx",
        "torchurl": "https://github.com/rymuelle/RawRefinery/releases/download/v1.2.1-alpha/ShadowWeightedL1_super_light.pt",
        "torchfilename": "ShadowWeightedL1_super_light.pt",
        "max_iso": 65535,
        "demosaicing": "Malvar2004",
        "conditioning": True,
    },
    "TreeNetDenoiseHeavy": {
        "url": "https://github.com/rymuelle/RawForge/releases/download/onnx_v1.0.0/ShadowWeightedL1_24_deep_500.onnx",
        "filename": "ShadowWeightedL1_24_deep_500.onnx",
        "torchurl": "https://github.com/rymuelle/RawRefinery/releases/download/v1.2.1-alpha/ShadowWeightedL1_24_deep_500.pt",
        "torchfilename": "ShadowWeightedL1_24_deep_500.pt",
        "max_iso": 65535,
        "demosaicing": "Malvar2004",
        "conditioning": True,
    },
    "Deblur": {
        "url": "https://github.com/rymuelle/RawForge/releases/download/onnx_v1.0.0/realblur_gamma_140.onnx",
        "filename": "realblur_gamma_140.onnx",
        "torchurl": "https://github.com/rymuelle/RawRefinery/releases/download/v1.2.1-alpha/realblur_gamma_140.pt",
        "torchfilename": "realblur_gamma_140.pt",
        "demosaicing": "Malvar2004",
        "conditioning": True,
    },
    "DeepSharpen": {
        "url": "https://github.com/rymuelle/RawForge/releases/download/onnx_v1.0.0/Deblur_deep_24.onnx",
        "filename": "Deblur_deep_24.onnx",
        "torchurl": "https://github.com/rymuelle/RawRefinery/releases/download/v1.2.1-alpha/Deblur_deep_24.pt",
        "torchfilename": "Deblur_deep_24.pt",
        "demosaicing": "Malvar2004",
        "conditioning": True,
    },
    "TreeNetDenoiseXTrans": {
        "url": "https://github.com/rymuelle/RawForge/releases/download/onnx_v1.0.0/xtrans_fixed_exposure_no_conditioning_400.onnx",
        "filename": "xtrans_fixed_exposure_no_conditioning_400.onnx",
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/xtrans_v1.0.0/xtrans_fixed_exposure_no_conditioning_400.pt",
        "torchfilename": "xtrans_fixed_exposure_no_conditioning_400.pt",
        "demosaicing": "rawpy",
        "conditioning": True,
        "batch_size": 1,
        "tile_size": 256,
        "cond_scale": 0,
    },
    "RestormerXTrans": {
        "url": "https://github.com/rymuelle/RawForge/releases/download/onnx_v1.0.0/restormer.onnx",
        "filename": "restormer.onnx",
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/xtrans_v1.0.0/restormer.pt",
        "torchfilename": "restormer.pt",
        "demosaicing": "rawpy",
        "conditioning": True,
        "batch_size": 1,
    },
    "JDD256": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DemoRestormerDiT_to_demo_cont.pt",
        "torchfilename": "DemoRestormerDiT_to_demo_cont.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 256,
        "subtract_bl": True,
        "image_clip": True,
    },
    "JDD": {
        "url": None,
        "filename": None,
        "torchurl": "https://github.com/rymuelle/RawForge/releases/download/JDD_v1.0.0/DemoRestormerDiT_to_demo_cont_cont_768_RawNIND.pt",
        "torchfilename": "DemoRestormerDiT_to_demo_cont_cont_768_RawNIND.pt",
        "demosaicing": "sixchan",
        "image_scale": 1,
        "conditioning": False,
        "batch_size": 1,
        "tile_size": 768,
        "subtract_bl": False,
        "image_clip": True,
    },
}

for model_config in MODEL_REGISTRY.values():
    model_config.setdefault("tile_size", 256)
    model_config.setdefault("tile_overlap", 0.25)
    model_config.setdefault("batch_size", 1)
    model_config.setdefault("conditioning", False)
